---
# yamllint disable rule:line-length
###############################################################################
# Repo Assert Settings
###############################################################################
# Sanity check options to stop preventable errors.

- name: 'Assert | required options'
  ansible.builtin.assert:
    quiet: true
    that:
      - repo_release_owner | length > 0 and
        repo_release_repo | length > 0 and
        repo_release_asset | length > 0 and
        repo_release_tag | length > 0
    fail_msg: |
      repo_release_owner, repo_release_repo, repo_release_asset, and
      repo_release_tag must be set.

      repo_release_owner: {{ repo_release_owner }}
      repo_release_repo: {{ repo_release_repo }}
      repo_release_asset: {{ repo_release_asset }}
      repo_release_tag: {{ repo_release_tag }}

- name: 'Assert | no templates in repo_release_asset_static_url'
  when: repo_release_asset_static_url | length > 0
  ansible.builtin.assert:
    quiet: true
    that:
      - '"{VERSION}" not in repo_release_asset'
      - '"{BARE_VERSION}" not in repo_release_asset'
    fail_msg: |
      Using repo_release_asset_static_url requires not using {VERSION}, {BARE_VERSION}
      in repo_release_asset.

      repo_release_asset: {{ repo_release_asset }}

- name: 'Assert | repo_release_asset_static_url no checksum or signature'
  when: repo_release_asset_static_url | length > 0
  ansible.builtin.assert:
    quiet: true
    that:
      - repo_release_checksum | length == 0
      - repo_release_signature | length == 0
    fail_msg: |
      repo_release_asset_static_url does NOT validate download.

      This is enforced to prevent the false sense of security for untrusted
      sites that provide checksums and signatures for downloads.

      repo_release_asset_static_url: {{ repo_release_asset_static_url }}
      repo_release_checksum: {{ repo_release_checksum }}
      repo_release_signature: {{ repo_release_signature }}

- name: 'Assert | GPG requires key or key ID'
  when: repo_release_signature | length > 0
  ansible.builtin.assert:
    quiet: true
    that:
      - repo_release_gpg_key_id | length > 0 or repo_release_gpg_key | length > 0
    fail_msg: |
      repo_release_signature requires key or key ID set.

      repo_release_gpg_key_id: {{ repo_release_gpg_key_id }}
      repo_release_gpg_key: {{ repo_release_gpg_key }}

- name: 'Assert | WARNING'
  when: >
    not (repo_testing_enable | default(false)) and
    repo_host_access_token | length == 0
  ansible.builtin.debug:
    msg: |
      No API token specified (repo_host_access_token).

      Downloads may fail due to rate limited anonymous API usage.

- name: 'Assert | WARNING'
  when: repo_release_asset_static_url | length > 0
  ansible.builtin.debug:
    msg: |
      WARNING: DOWNLOAD CANNOT BE VERIFIED.

      Static URLs should ONLY be used for repositories without versioning which
      release compiled binaries from a separate URL. These downloads can
      contain malicious code and should be UNTRUSTED by default.

      {{ repo_release_asset_static_url }}

- name: 'Assert | WARNING'
  when: repo_extract_delete_old_versions
  ansible.builtin.debug:
    msg: |
      Delete old extracted archive versions enabled.

      Existing directories in {{ repo_extract_dir }} will be deleted if they do
      not match the current specified version. Only directories matching
      {{ repo_release_repo }} will be considered for deletion.

      DATA DESTRUCTIVE.
