---
###############################################################################
# Repo Download
###############################################################################
# Download specified asset to staging.
#
# Args:
#   __repo_stage_asset: dict - staged asset metadata.
#   __repo_stage_test: str - test dictionary key to use if testing.
#   __repo_staging_dir: str - Staging location for downloads, extracts.

- name: 'Download | {{ __repo_stage_asset.name }}'
  when: not (repo_testing_enable | default(false))
  ansible.builtin.get_url:
    url: '{{ __repo_stage_asset.browser_download_url }}'
    dest: '{{ __repo_staging_dir }}/{{ __repo_stage_asset.name }}'
    owner: '{{ repo_file_owner }}'
    group: '{{ repo_file_group }}'
    mode: '{{ repo_extract_mode }}'
    headers:
      Authorization: '{{ repo_host_access_token | default(omit) }}'
  register: _repo_download
  until: _repo_download is succeeded
  retries: '{{ repo_download_retries }}'
  delay: 2

- name: 'Download | inject downloaded archive'
  when: (repo_testing_enable | default(false))
  ansible.builtin.copy:
    src: '{{
        repo_testing_versions[__repo_cache_test_index | int][__repo_stage_test]
      }}'
    dest: '{{ __repo_staging_dir }}/{{ __repo_stage_asset.name }}'
    owner: '{{ repo_file_owner }}'
    group: '{{ repo_file_group }}'
    mode: '{{ repo_extract_mode }}'
