---
- name: 'Assert'
  ansible.builtin.include_tasks: 'assert.yml'

- name: 'Install packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ repo_role_packages }}'
      - '{{
          repo_role_gpg_packages
          if repo_release_signature | length > 0 else
          []
        }}'
    apt_package_update_cache: true

- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'
- name: 'Stage'
  ansible.builtin.include_tasks: 'stage.yml'
- name: 'Extract'
  ansible.builtin.include_tasks: 'extract.yml'
