---
# yamllint disable rule:line-length
# Role variable returned variables are scoped to the current play only (e.g.
# converge.yml) and must be tested between each application of the role. Test
# these values while converging versus verify.yml (where scoping will prevent)
# testing these values.
#
# Roles consuming this role do not need to test this way.
- name: 'Extract delete migration | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration | converge | apply r_pufky.srv.repo (v1.0.0)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.repo'
      vars:
        repo_release_type: 'tar.gz'
        repo_release_owner: 'leetreleaser'
        repo_release_repo: 'test-repo'
        repo_release_tag: 'latest'
        file_owner: 'root'
        file_group: 'root'
        repo_extract_dir: '/opt/test-repo-gz'
        repo_extract_symlink_target: '/opt/test-repo-gz/test-repo'
        repo_extract_extra_opts: '--strip-components=1'
        repo_extract_mode: 'a-st,o-rwx'
        repo_extract_remove_files:
          - 'README.md'
          - '.hidden_file'
        repo_extract_migrate_files: ['config/db/db_skeleton_file.db']

    - name: 'Extract delete migration | converge | add non-repo directory'
      ansible.builtin.file:
        path: '/opt/test-repo-gz/this_dir_should_not_be_removed'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'

    - name: 'Extract delete migration | converge | add non-repo directory'
      ansible.builtin.file:
        path: '/opt/test-repo-gz/this_file_should_not_be_removed'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'touch'

- name: 'Extract delete migration | converge | migrate data'
  hosts: 'repo-debian-12-extract_delete_migration'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration | converge | apply r_pufky.srv.repo (v1.0.1)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.repo'
      vars:
        repo_release_type: 'tar.gz'
        repo_release_owner: 'leetreleaser'
        repo_release_repo: 'test-repo'
        repo_release_tag: 'latest'
        file_owner: 'root'
        file_group: 'root'
        repo_extract_dir: '/opt/test-repo-gz'
        repo_extract_symlink_target: '/opt/test-repo-gz/test-repo'
        repo_extract_extra_opts: '--strip-components=1'
        repo_extract_mode: 'a-st,o-rwx'
        repo_extract_remove_files:
          - 'README.md'
          - '.hidden_file'
        repo_extract_migrate_files:
          - 'config/db/db_skeleton_file.db'
          - 'non_existing_file_should_be_skipped_no_errors'
          - 'nested_migration'
        repo_extract_delete_old_versions: true

- name: 'Extract delete migration | converge | no migration'
  hosts: 'repo-debian-12-extract_delete_migration-no-keep'
  gather_facts: false
  tasks:
    - name: 'Extract delete migration | converge | apply r_pufky.srv.repo (v1.0.1)'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.repo'
      vars:
        repo_release_type: 'tar.gz'
        repo_release_owner: 'leetreleaser'
        repo_release_repo: 'test-repo'
        repo_release_tag: 'latest'
        file_owner: 'root'
        file_group: 'root'
        repo_extract_dir: '/opt/test-repo-gz'
        repo_extract_symlink_target: '/opt/test-repo-gz/test-repo'
        repo_extract_extra_opts: '--strip-components=1'
        repo_extract_mode: 'a-st,o-rwx'
        repo_extract_remove_files:
          - 'README.md'
          - '.hidden_file'
        repo_extract_delete_old_versions: true
