---
# yamllint disable rule:line-length
# Role variable returned variables are scoped to the current play only (e.g.
# converge.yml) and must be tested between each application of the role. Test
# these values while converging versus verify.yml (where scoping will prevent)
# testing these values.
#
# Roles consuming this role do not need to test this way.
- name: 'Pre release | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Pre release | converge | apply r_pufky.srv.repo'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.repo'
      vars:
        repo_release_type: 'tar.gz'
        repo_release_owner: 'leetreleaser'
        repo_release_repo: 'test_repo'
        repo_release_tag: 'latest'
        repo_extract_dir: '/opt/test_repo_gz'

    - name: 'Pre release | converge | assert pre-release target URL'
      ansible.builtin.assert:
        that:
          - _repo_target == 'v1.0.0'
          - _repo_target_url == 'http://example.com/pre_tar'
          - _repo_archive == '/tmp/test_repo-v1.0.0.tar.gz'
          - _repo_dir == '/opt/test_repo_gz/test_repo-v1.0.0'
          - _repo_remote_metadata is mapping
