---
###############################################################################
# Repo Download Manager
###############################################################################
#
# Reference:
# * https://docs.github.com/en/rest/about-the-rest-api/api-versions
# * https://codeberg.org/api/swagger

# Last time github options were validated against a default configuration.
repo_role_validate_date: '2024-06-22'
repo_role_validate_release: 'bookworm'

# Role checked against this version of the API.
repo_role_github_api_version: '2022-11-28'
repo_role_codeberg_api_version: 'v1'

repo_role_gpg_key_server: 'hkps://keys.openpgp.org'

###############################################################################
# Host API Endpoints
###############################################################################
# API endpoint to query for release information. Additional endpoints may be
# used if they match the general github API.
#
# Currently variable defined header keys do not resolve.
#
# Reference:
# * https://docs.github.com/en/rest/releases
# * https://codeberg.org/api/swagger

repo_role_host:
  github:
    api: 'https://api.github.com/repos'
    base: 'https://github.com'
    auth_header: 'Authorization'
  codeberg:
    api: 'https://codeberg.org/api/v1/repos'
    base: 'https://codeberg.org'
    auth_header: 'AuthorizationHeaderToken'

###############################################################################
# APT Packages
###############################################################################

repo_role_packages:
  - 'ca-certificates'  # SSL support for ansible.builtin.get_url.
  - 'unzip'  # zip archives.
  - 'xz-utils'  # xz archives.

repo_role_gpg_packages:
  - 'gnupg2'
