---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'
        _test_files:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files'

    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | check testing key'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/466EEC2B67516C7117C85CE3A0BC35D16698BAB9.asc'
      register: _test_prepare

    - name: 'Prepare | export testing key file'
      when: not _test_prepare.stat.exists
      ansible.builtin.get_url:
        url: 'https://keys.openpgp.org/vks/v1/by-fingerprint/466EEC2B67516C7117C85CE3A0BC35D16698BAB9'  # yamllint disable-line rule:line-length
        dest: '{{ _test_cache }}/466EEC2B67516C7117C85CE3A0BC35D16698BAB9.asc'
        mode: '0640'

    - name: 'Prepare | check test_archive_v1.0.0.tar.gz.sah256'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/test_archive_v1.0.0.tar.gz'
      register: _test_prepare

    - name: 'Prepare | generate test_archive_v1.0.0.tar.gz.sha256'
      when: not _test_prepare.stat.exists
      ansible.builtin.shell: >
        set -o pipefail &&
        sha256sum 'test_archive_v1.0.0.tar.gz' >
        '{{ _test_cache }}/test_archive_v1.0.0.tar.gz.sha256'
      args:
        chdir: '{{ _test_files }}'
      changed_when: true

    - name: 'Prepare | check test_archive_v1.0.0.tar.xz.sah256'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/test_archive_v1.0.0.tar.xz'
      register: _test_prepare

    - name: 'Prepare | generate test_archive_v1.0.0.tar.xz.sha256'
      when: not _test_prepare.stat.exists
      ansible.builtin.shell: >
        set -o pipefail &&
        sha256sum 'test_archive_v1.0.0.tar.xz' >
        '{{ _test_cache }}/test_archive_v1.0.0.tar.xz.sha256'
      args:
        chdir: '{{ _test_files }}'
      changed_when: true

    - name: 'Prepare | check test_archive_v1.0.0.zip.sha256'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/test_archive_v1.0.0.zip'
      register: _test_prepare

    - name: 'Prepare | generate test_archive_v1.0.0.zip.sha256'
      when: not _test_prepare.stat.exists
      ansible.builtin.shell: >
        set -o pipefail &&
        sha256sum 'test_archive_v1.0.0.zip' >
        '{{ _test_cache }}/test_archive_v1.0.0.zip.sha256'
      args:
        chdir: '{{ _test_files }}'
      changed_when: true

    - name: 'Prepare | create testing binary test_binary_v1.0.0'
      ansible.builtin.copy:
        src: '{{ _test_files }}/test_archive_v1.0.0.zip'
        dest: '{{ _test_cache }}/test_binary_v1.0.0'
        mode: '0640'
