---
- name: 'Default | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Default | prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'
        _test_files:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files'

    - name: 'Default | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Default | prepare | create cache'

    - name: 'Default | prepare | check test_archive_v1.0.0.tar.gz.sah256'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/test_archive_v1.0.0.tar.gz'
      register: _test_prepare

    - name: 'Default | prepare | generate test_archive_v1.0.0.tar.gz.sha256'
      when: not _test_prepare.stat.exists
      ansible.builtin.shell: >
        set -o pipefail &&
        sha256sum 'test_archive_v1.0.0.tar.gz' >
        '{{ _test_cache }}/test_archive_v1.0.0.tar.gz.sha256'
      args:
        chdir: '{{ _test_files }}'
      changed_when: true

    - name: 'Default | prepare | check test_archive_v1.0.0.zip.sha256'
      ansible.builtin.stat:
        path: '{{ _test_cache }}/test_archive_v1.0.0.zip'
      register: _test_prepare

    - name: 'Default | prepare | generate test_archive_v1.0.0.zip.sha256'
      when: not _test_prepare.stat.exists
      ansible.builtin.shell: >
        set -o pipefail &&
        sha256sum 'test_archive_v1.0.0.zip' >
        '{{ _test_cache }}/test_archive_v1.0.0.zip.sha256'
      args:
        chdir: '{{ _test_files }}'
      changed_when: true
