---
# yamllint disable rule:line-length
# Catch assertion errors as the role is called.
#
# Roles consuming this role do not need to test this way.
- name: 'Assert requirements | converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Assert requirements | converge | required options | owner'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_repo: 'test_repo'
        repo_release_asset: 'test_asset'
        repo_release_tag: 'test_tag'
        test_name: 'required options | owner'
        test_fail_message: 'repo_release_owner missing did not trigger assertion.'

    - name: 'Assert requirements | converge | required options | release'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_owner: 'test_owner'
        repo_release_asset: 'test_asset'
        repo_release_tag: 'test_tag'
        test_name: 'required options | release'
        test_fail_message: 'repo_release_repo missing did not trigger assertion.'

    - name: 'Assert requirements | converge | required options | asset'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_owner: 'test_owner'
        repo_release_repo: 'test_repo'
        repo_release_tag: 'test_tag'
        test_name: 'required options | asset'
        test_fail_message: repo_release_asset missing did not trigger assertion.'

    - name: 'Assert requirements | converge | required options | tag'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_owner: 'test_owner'
        repo_release_repo: 'test_repo'
        repo_release_asset: 'test_asset'
        repo_release_tag: ''
        test_name: 'required options | tag'
        test_fail_message: 'repo_release_tag missing did not trigger assertion.'

    - name: 'Assert requirements | converge | required options | all'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_tag: ''
        test_name: 'required options | all'
        test_fail_message: 'repo_release_* missing did not trigger assertion.'

    - name: 'Assert requirements | converge | required options | static URL | no templates'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_owner: 'test_owner'
        repo_release_repo: 'test_repo'
        repo_release_asset: 'asset-{VERSION}.tar.gz'
        repo_release_asset_static_url: 'https://example.com'
        test_name: 'required options | static URL | no templates'
        test_fail_message: 'repo_release_asset template did not trigger assertion.'

    - name: 'Assert requirements | converge | required options | static URL | no GPG'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_owner: 'test_owner'
        repo_release_asset: 'test_asset'
        repo_release_repo: 'test_repo'
        repo_release_signature: 'test_asset_signature.asc'
        repo_release_asset_static_url: 'https://example.com'
        test_name: 'required options | static URL | no GPG'
        test_fail_message: 'repo_release_asset_static_url with signature did not trigger assertion.'

    - name: 'Assert requirements | converge | required options | GPG'
      ansible.builtin.include_tasks: 'tests/assert.yml'
      vars:
        repo_release_owner: 'test_owner'
        repo_release_asset: 'test_asset'
        repo_release_repo: 'test_repo'
        repo_release_signature: 'test_asset_signature.asc'
        test_name: 'required options | GPG'
        test_fail_message: 'repo_release_signature no key,key ID did not trigger assertion.'
