---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.repo (v1.0.0)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.repo'
      vars:
        repo_release_asset: 'test_archive_v1.0.0.tar.gz'
        repo_extract_migrate_files: ['config/db/db_skeleton_file.db']

    - name: 'Converge | add non-repo directory'
      ansible.builtin.file:
        path: '/opt/test_repo_gz/this_dir_should_not_be_removed'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'directory'

    - name: 'Converge | add non-repo directory'
      ansible.builtin.file:
        path: '/opt/test_repo_gz/this_file_should_not_be_removed'
        owner: 'root'
        group: 'root'
        mode: '0755'
        state: 'touch'

- name: 'Converge | migrate data'
  hosts: 'repo-debian-13-migration'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.repo (v1.0.1)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.repo'
      vars:
        repo_release_asset: 'test_archive_v1.0.1.tar.gz'
        repo_extract_migrate_files:
          - 'config/db/db_skeleton_file.db'
          - 'non_existing_file_should_be_skipped_no_errors'
          - 'nested_migration'
        repo_extract_delete_old_versions: true

- name: 'Converge | no migration'
  hosts: 'repo-debian-13-migration-no-keep'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.repo (v1.0.1)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.repo'
      vars:
        repo_release_asset: 'test_archive_v1.0.1.tar.gz'
        repo_extract_delete_old_versions: true
