---
###############################################################################
# Migration
###############################################################################
# Ensure files are migrated correctly.
#
# Tests:
# * Releases are installed and migrated to the new version.
# * Migrated files are kept to v1.0.0.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        repo_release_owner: 'test_owner'
        repo_release_repo: 'test_repo'
        repo_extract_dir: '/opt/test_repo_gz'
        repo_extract_symlink: '/opt/test_repo_gz/test_repo'
        repo_extract_extra_opts: '--strip-components=1'
        repo_extract_mode: 'a-st,o-rwx'
        repo_extract_remove_files:
          - 'README.md'
          - '.hidden_file'
        repo_testing_enable: true
        repo_testing_versions:
          - version: 'v1.0.0'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/files/test_archive_v1.0.0.tar.gz"
              }}'
          - version: 'v1.0.1'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/files/test_archive_v1.0.1.tar.gz"
              }}'
          - version: 'v1.0.1'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/files/test_archive_v1.0.1.tar.gz"
              }}'
platforms:
  - name: 'repo-debian-13-migration'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'repo-debian-13-migration-no-keep'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
